// L'index représente le véritable id des catégories
export const translatedCategories: { [key: number]: string } = {
  9: 'Connaissances générales',
  10: 'Divertissement : Livres',
  11: 'Divertissement : Film',
  12: 'Divertissement : Musique',
  13: 'Divertissement : Comédies musicales et théâtres',
  14: 'Divertissement : Télévision',
  15: 'Divertissement : Jeux vidéo',
  16: 'Divertissement : Jeux de société',
  17: 'Sciences et nature',
  18: 'Sciences : Informatique',
  19: 'Sciences : Mathématiques',
  20: 'Mythologie',
  21: 'Sports',
  22: 'Géographie',
  23: 'Histoire',
  24: 'Politique',
  25: 'Art',
  26: 'Célébrités',
  27: 'Animaux',
  28: 'Véhicules',
  29: 'Divertissement : Bandes dessinées',
  30: 'Sciences : Gadgets',
  31: 'Divertissement : Anime japonais et manga',
  32: 'Divertissement : Dessins animés et animations',
};
